#!/usr/bin/env python3

import py_compile
import argparse

def main():
    parser = argparse.ArgumentParser("CPython pyc compile driver")
    parser.add_argument("input")
    parser.add_argument("-o", "--output", required=True)
    args = parser.parse_args()
    py_compile.compile(args.input, args.output)

if __name__ == "__main__":
    main()
